# Tailnet control panel (OliveTin) — a small web UI on port 80 of the
# tailnet address (<hostname>.headscale.local), giving buttons for shell
# commands ("actions"). Other modules extend it declaratively:
#
#   sys.controlPanel.actions.restartFoo = {
#     shell = "systemctl restart foo";
#     unit = "foo.service";   # -> generates a polkit rule for this unit
#   };
#
# Actions run as the unprivileged "olivetin" user; anything that needs
# privilege must go through polkit (declare `unit`) or a group the user is
# added to (sys.controlPanel.extraGroups, e.g. "docker").
#
# Exposure: if nginx runs on the host (it owns the tailnet IP), the panel
# binds 127.0.0.1 and nginx routes the <hostname>.headscale.local vhost to
# it; otherwise OliveTin binds <sys.bindAddress>:<port> directly.
{
  lib,
  config,
  pkgs,
  ...
}: let
  cfg = config.sys.controlPanel;
  fqdn = "${config.sys.hostName}.${cfg.dnsDomain}";
  behindNginx = config.services.nginx.enable;

  actionType = lib.types.submodule {
    options = {
      title = lib.mkOption {
        type = lib.types.str;
        default = "";
        description = "Button label; defaults to the action name.";
      };
      shell = lib.mkOption {
        type = lib.types.str;
        description = "Shell command the button runs.";
      };
      icon = lib.mkOption {
        type = lib.types.str;
        default = "bolt";
        description = "OliveTin icon name (e.g. \"restart\") or arbitrary HTML.";
      };
      timeout = lib.mkOption {
        type = lib.types.nullOr lib.types.int;
        default = null;
        description = "Seconds after which the command is killed.";
      };
      confirmation = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Ask for confirmation before running.";
      };
      group = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "OliveTin action group, for concurrency/rate limiting.";
      };
      unit = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = ''
          systemd unit this action manages. Generates a polkit rule that lets
          the olivetin user start/stop/restart exactly this unit (and nothing
          else), so the shell command can be plain `systemctl <verb> unit`.
        '';
      };
    };
  };

  resolveTitle = name: action:
    if action.title != ""
    then action.title
    else name;

  oliveActions =
    lib.mapAttrsToList
    (
      name: action:
        {
          id = name;
          title = resolveTitle name action;
          inherit (action) shell icon;
        }
        // lib.optionalAttrs (action.timeout != null) {
          timeout = action.timeout;
        }
        // lib.optionalAttrs (action.group != null) {
          groups = [action.group];
        }
        // lib.optionalAttrs action.confirmation {
          arguments = [
            {
              type = "confirmation";
              title = "Are you sure?";
            }
          ];
        }
    )
    cfg.actions;

  actionTitles = lib.mapAttrsToList resolveTitle cfg.actions;

  managedUnits = lib.filter (unit: unit != null) (lib.mapAttrsToList (_: action: action.unit) cfg.actions);

  polkitRule = ''
    // Generated by modules/services/control-panel.nix. Lets the olivetin
    // control panel user manage exactly the systemd units referenced by
    // declared actions, and nothing else. NB: this file is JavaScript, so
    // comments must be // (a # anywhere breaks compilation of the whole
    // rules file and silently disables every rule in it).
    polkit.addRule(function(action, subject) {
      if (action.id == "org.freedesktop.systemd1.manage-units" &&
          subject.user == "olivetin") {
        var allowedUnits = [${lib.concatMapStringsSep ", " (unit: ''"${unit}"'') managedUnits}];
        if (allowedUnits.indexOf(action.lookup("unit")) >= 0) {
          return polkit.Result.YES;
        }
      }
    });
  '';

  # Tailscale peers as OliveTin entity instances: one record per peer with
  # the MagicDNS name (for the link), the tailnet IP, reachability, and the
  # status color interpolated into the dashboard display's style attribute.
  tailnetHostsScript =
    pkgs.writers.writePython3 "control-panel-tailnet-hosts" {
      flakeIgnore = ["E501"];
    } ''
      import json
      import shutil
      import subprocess
      import sys
      from pathlib import Path

      TAILSCALE_BIN = "${lib.getExe config.services.tailscale.package}"
      ENTITIES_DIR = Path("/var/lib/olivetin/entities")
      TARGET = ENTITIES_DIR / "tailnet-hosts.json"
      TMP = ENTITIES_DIR / ".tailnet-hosts.new"

      COLOR_ONLINE = "#3fb950"
      COLOR_OFFLINE = "#9ca3af"


      def build_records(status):
          peers = status.get("Peer") or {}
          self_id = (status.get("Self") or {}).get("ID")
          records = []
          for key, peer in peers.items():
              if self_id is not None and key == self_id:
                  continue
              dns = (peer.get("DNSName") or "").rstrip(".")
              ip = (peer.get("TailscaleIPs") or [""])[0]
              hostname = peer.get("HostName") or ""
              online = bool(peer.get("Online"))
              title = hostname or (dns.split(".")[0] if dns else ip)
              if not title:
                  continue
              records.append({
                  "title": title,
                  "dnsName": dns,
                  "ip": ip,
                  "online": online,
                  "status": "Online" if online else "Offline",
                  "statusColor": COLOR_ONLINE if online else COLOR_OFFLINE,
                  "url": "http://" + (dns or ip) + "/",
              })
          records.sort(key=lambda record: record["title"].casefold())
          return records


      def main():
          ENTITIES_DIR.mkdir(parents=True, exist_ok=True)
          try:
              proc = subprocess.run(
                  [TAILSCALE_BIN, "status", "--json"], capture_output=True, text=True
              )
          except OSError:
              proc = None
          if proc is None or proc.returncode != 0:
              print("tailscale status failed; keeping previous entity file")
              return 0

          records = build_records(json.loads(proc.stdout))
          content = "".join(
              json.dumps(record, sort_keys=True, separators=(",", ":")) + "\n"
              for record in records
          )

          if TARGET.exists() and TARGET.read_text() == content:
              return 0
          TMP.write_text(content)
          # Copy in place so the target keeps its inode: OliveTin watches the
          # file and live-reloads on modification (a rename would orphan the
          # watch). JSON entity files are parsed as JSONL, one object per line.
          shutil.copyfile(TMP, TARGET)
          TMP.unlink()
          return 0


      if __name__ == "__main__":
          sys.exit(main())
    '';
in {
  options.sys.controlPanel = {
    enable = lib.mkEnableOption "the tailnet control panel (OliveTin) on this host";

    port = lib.mkOption {
      type = lib.types.port;
      default = 80;
      description = ''
        Tailnet-side HTTP port. With nginx on the host this is the port of the
        vhost for ${fqdn}; without nginx, the port OliveTin binds directly.
      '';
    };

    internalPort = lib.mkOption {
      type = lib.types.port;
      default = 1337;
      description = "Loopback port OliveTin binds when proxied through nginx.";
    };

    dnsDomain = lib.mkOption {
      type = lib.types.str;
      default = "headscale.local";
      description = "Tailnet DNS domain (headscale dns.base_domain) for the vhost name.";
    };

    extraGroups = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      description = ''
        Extra groups for the olivetin user, granting actions access to
        group-gated resources (e.g. "docker" for container commands).
      '';
    };

    actions = lib.mkOption {
      type = lib.types.attrsOf actionType;
      default = {};
      description = ''
        Actions (buttons) for the control panel. The attribute name becomes
        the stable OliveTin action id (used by the REST API/webhooks), so it
        must not change even if the title is reworded.
      '';
      example = {
        restartFoo = {
          shell = "systemctl restart foo";
          unit = "foo.service";
          icon = "restart";
          confirmation = true;
        };
      };
    };

    links = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule {
        options = {
          title = lib.mkOption {
            type = lib.types.str;
            description = "Link text shown on the Services dashboard.";
          };
          url = lib.mkOption {
            type = lib.types.str;
            description = "Target URL, rendered as a plain anchor element.";
          };
        };
      });
      default = {};
      description = ''
        Service links for the panel's "Services" dashboard. Any module can
        declare a link (e.g. hermes-tunnel.nix). The dashboard only exists
        when at least one link is declared.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = lib.length (lib.unique actionTitles) == lib.length actionTitles;
        message = "Control panel action titles must be unique (OliveTin hides duplicates): ${
          lib.concatStringsSep ", " actionTitles
        }";
      }
    ];

    # Bind <sys.bindAddress>:80 before tailscale0 actually carries the
    # address; traffic only flows once tailscaled is up (same pattern as the
    # nginx vhosts; noether sets this at host level too).
    boot.kernel.sysctl."net.ipv4.ip_nonlocal_bind" = lib.mkDefault 1;

    services.olivetin = {
      enable = true;
      # The 2k series currently ships unpatched security fixes only in 3k
      # (nixpkgs#498611); the module default would pick 2k for stateVersion
      # < 26.05.
      package = pkgs.olivetin-3k;
      path = with pkgs; [bash systemd];
      settings = {
        ListenAddressSingleHTTPFrontend =
          if behindNginx
          then "127.0.0.1:${toString cfg.internalPort}"
          else "${config.sys.bindAddress}:${toString cfg.port}";
        pageTitle = "${config.sys.hostName} control panel";
        actions = oliveActions;
        entities = [
          {
            file = "/var/lib/olivetin/entities/tailnet-hosts.json";
            name = "tailnetHost";
          }
        ];
        dashboards =
          [
            {
              title = "Home";
              contents = [
                {
                  title = "Actions";
                  type = "fieldset";
                  contents =
                    lib.mapAttrsToList
                    (name: action: {title = resolveTitle name action;})
                    cfg.actions;
                }
                {
                  type = "fieldset";
                  entity = "tailnetHost";
                  title = "Tailnet host: {{ tailnetHost.title }}";
                  contents = [
                    {
                      type = "display";
                      # The color arrives as a plain string from the entity
                      # data (statusColor) and is interpolated into the style
                      # attribute — no HTML travels through templating.
                      title = ''
                        <a href="{{ tailnetHost.url }}">{{ tailnetHost.title }}</a><br />
                        IP: <strong>{{ tailnetHost.ip }}</strong><br />
                        Status: <strong style="color: {{ tailnetHost.statusColor }}">{{ tailnetHost.status }}</strong>
                      '';
                    }
                  ];
                }
              ];
            }
          ]
          # A Services dashboard only exists when some module declares links.
          ++ lib.optional (cfg.links != {}) {
            title = "Services";
            contents = [
              {
                title = "Services";
                type = "fieldset";
                # URLs/titles are baked into config.yaml at Nix level — no
                # templating. attrset iteration is name-sorted, so the tile
                # order is stable.
                contents =
                  lib.mapAttrsToList
                  (
                    name: link: {
                      type = "display";
                      title = ''<a href="${link.url}">${link.title}</a>'';
                    }
                  )
                  cfg.links;
              }
            ];
          };
      };
    };

    # Port 80 without being root; systemd grants the bind capability and it
    # is dropped on exec of every action.
    systemd.services.olivetin.serviceConfig = {
      AmbientCapabilities = ["CAP_NET_BIND_SERVICE"];
      StateDirectory = "olivetin";
      ProtectHome = true;
      ProtectSystem = "full";
      PrivateTmp = true;
      LockPersonality = true;
      RestrictRealtime = true;
    };

    systemd.services.control-panel-tailnet-hosts = {
      description = "Refresh control panel tailnet host entities";
      after = ["tailscaled.service"];
      wantedBy = ["multi-user.target"];
      serviceConfig = {
        Type = "oneshot";
        User = "olivetin";
        Group = "olivetin";
        StateDirectory = "olivetin";
        SyslogIdentifier = "control-panel-tailnet-hosts";
      };
      script = "${tailnetHostsScript}";
    };

    systemd.timers.control-panel-tailnet-hosts = {
      wantedBy = ["timers.target"];
      timerConfig = {
        OnBootSec = "15s";
        OnUnitActiveSec = "30s";
        AccuracySec = "10s";
      };
    };

    security.polkit.extraConfig = lib.mkIf (managedUnits != []) polkitRule;

    users.users.olivetin.extraGroups = cfg.extraGroups;

    # The panel rides nginx's existing vhost routing on the tailnet address
    # (same pattern as hermes): name-based on the shared addr:port socket,
    # with the tailnet-reserved default_server still dropping unmatched
    # Hosts. The bare node name resolves via MagicDNS without an extra
    # headscale record.
    services.nginx.virtualHosts.${fqdn} = lib.mkIf behindNginx {
      listen = [
        {
          addr = config.sys.bindAddress;
          port = cfg.port;
          ssl = false;
        }
      ];
      serverName = fqdn;
      locations."/" = {
        proxyPass = "http://127.0.0.1:${toString cfg.internalPort}";
        proxyWebsockets = true; # OliveTin streams updates over a websocket
        extraConfig = ''
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_read_timeout 300;
          proxy_send_timeout 300;
        '';
      };
      extraConfig = ''
        access_log /var/log/nginx/control-panel_access.log;
        error_log /var/log/nginx/control-panel_error.log;
      '';
    };
  };
}
