{
  lib,
  config,
  ...
}: {
  # The mautrix bridge packages depend on the low-level Matrix crypto library
  # olm 3.x, which nixpkgs marks as insecure. Only needed when running the
  # Matrix homeserver appservices.
  nixpkgs.config.permittedInsecurePackages = ["olm-3.2.16"];

  services.matrix-tuwunel = {
    enable = true;
    settings.global = {
      server_name = "matrix.jonbyr.com";
      address = ["127.0.0.1"]; # Served via nginx reverse proxy; not exposed on the network
      port = [34751];
      allow_federation = true;
      # Registration is gated by a token stored out-of-band at
      # /etc/tuwunel-registration-token (root:tuwunel 0640; the service reads it
      # via the tuwunel group, see systemd.services.tuwunel below). Without a
      # token (or the explicit `yes_i_am_very_very_sure...` flag) tuwunel
      # refuses to start.
      allow_registration = true;
      registration_token_file = "/etc/tuwunel-registration-token";
      # Application services (bridges): load registration YAML files dropped
      # into this directory at startup. The mautrix-signal registration is
      # copied here by the tuwunel unit's ExecStartPre (see
      # systemd.services.tuwunel below); bridge tokens stay out of the nix
      # store in the bridge's own /var/lib directory.
      appservice_dir = "/var/lib/tuwunel/appservices";
      # MatrixRTC/Element Call support: advertise the Livekit SFU to clients.
      # `client` (and `server`) must be set or tuwunel 404s the .well-known
      # files instead of serving them.
      well_known = {
        client = "https://matrix.jonbyr.com";
        server = "matrix.jonbyr.com:443";
        livekit_url = "https://matrix-rtc.jonbyr.com";
      };
    };
  };

  # MatrixRTC: Livekit SFU + JWT issuer. Requires the shared credential file
  # /etc/livekit-secrets (`<keyname>: <secret>`, root 0600) created out-of-band.
  services.livekit = {
    enable = true;
    keyFile = "/etc/livekit-secrets";
    settings = {
      port = 7880; # control plane; reached via nginx on loopback only
      rtc = {
        tcp_port = 7881;
        port_range_start = 50100;
        port_range_end = 50200;
        node_ip = "167.233.73.190"; # Hetzner: public IP bound to the interface
        use_external_ip = false;
      };
      turn = {
        enabled = true;
        udp_port = 3478;
        relay_range_start = 50300;
        relay_range_end = 65535;
        domain = "matrix-rtc.jonbyr.com";
      };
    };
  };

  services.lk-jwt-service = {
    enable = true;
    keyFile = "/etc/livekit-secrets";
    livekitUrl = "wss://matrix-rtc.jonbyr.com";
    port = 8091; # reached via nginx on loopback only (8081 is dufs)
  };
  systemd.services.lk-jwt-service.environment.LIVEKIT_FULL_ACCESS_HOMESERVERS = "matrix.jonbyr.com";

  # Tuwunel runs as a runtime (DynamicUser) identity; put it in the static
  # `tuwunel` group so the registration token file can stay root:tuwunel 0640.
  # The bridge units' health must be up before us, because their PreStarts
  # generate the appservice registrations we copy into `appservice_dir`
  # (Tuwunel only reads that directory at startup).
  systemd.services.tuwunel = {
    # The tuwunel group for reading the registration token file, plus the
    # mautrix-signal/mautrix-whatsapp groups so the ExecStartPre below can
    # read the bridges' generated registrations (640, owned by each bridge)
    # and copy them into appservice_dir.
    serviceConfig.SupplementaryGroups = [
      "tuwunel"
      "mautrix-signal"
      "mautrix-whatsapp"
    ];
    after = ["mautrix-signal.service" "mautrix-whatsapp.service"];
    wants = ["mautrix-signal.service" "mautrix-whatsapp.service"];
    preStart = ''
      install -d -o tuwunel -g tuwunel -m 0755 /var/lib/tuwunel/appservices
      install -m 0644 \
        /var/lib/mautrix-signal/signal-registration.yaml \
        /var/lib/tuwunel/appservices/
      install -m 0644 \
        /var/lib/mautrix-whatsapp/whatsapp-registration.yaml \
        /var/lib/tuwunel/appservices/
    '';
  };

  # Signal bridge appservice. Registration YAML is generated by the module
  # (random as/hs tokens live in /var/lib/mautrix-signal, outside the store),
  # then copied to Tuwunel's appservice_dir by tuwunel's ExecStartPre above.
  # Basic mode for now: no encryption pickle key, no double-puppeting.
  services.mautrix-signal = {
    enable = true;
    registerToSynapse = false; # served via Tuwunel's appservice_dir instead
    settings = {
      homeserver = {
        address = "http://127.0.0.1:34751"; # Tuwunel client-server API
        domain = "matrix.jonbyr.com";
      };
      appservice.hostname = "127.0.0.1"; # loopback only (module default [::])
      # mautrix v2 refuses to start while bridge.permissions holds nothing but
      # the placeholder entries; grant a real user (see IsConfigured()).
      bridge.permissions = {
        "*" = "relay"; # everyone else gets relay mode only
        "@jonas:matrix.jonbyr.com" = "admin";
      };
      # Enables the transfer-archive request during (re)login: the bridge then
      # creates portals for all existing DMs *and* groups and backfills history
      # on connect. Without this, only live events create rooms.
      backfill = {
        enabled = true;
        max_catchup_messages = 500;
        unread_hours_threshold = 720;
      };
    };
  };

  # WhatsApp bridge appservice. Same registration dance as the Signal bridge:
  # the module generates whatsapp-registration.yaml with random as/hs tokens in
  # /var/lib/mautrix-whatsapp (outside the store), copied to Tuwunel's
  # appservice_dir by tuwunel's ExecStartPre above.
  # Basic mode: no encryption pickle key, no double-puppeting.
  services.mautrix-whatsapp = {
    enable = true;
    registerToSynapse = false; # served via Tuwunel's appservice_dir instead
    settings = {
      homeserver = {
        address = "http://127.0.0.1:34751"; # Tuwunel client-server API
        domain = "matrix.jonbyr.com";
      };
      appservice.hostname = "127.0.0.1"; # loopback only (module default [::])
      bridge.permissions = {
        "*" = "relay"; # everyone else gets relay mode only
        "@jonas:matrix.jonbyr.com" = "admin";
      };
      # WhatsApp connector settings live under `network.`: mxmain proxies the
      # connector config into that section and it is the only one the bridge
      # reads (top-level duplicates get dropped by the config upgrade).
      # DeviceProps.HistorySyncConfig is only advertised to the phone when all
      # three full_sync_config values are non-zero (connector.go Init); with
      # them unset (the default) many phones never push the history-sync blob
      # at all - which is why chats/messages never arrived even though
      # contacts (app state) kept working.
      network = {
        identity_change_notices = true;
        initial_auto_reconnect = true; # re-request sync after connection drops
        history_sync = {
          request_full_sync = true; # ask WhatsApp for full history
          max_initial_conversations = -1; # portal EVERY chat (DMs + groups)
          dispatch_wait = "1m"; # wait for all chunks before creating portals
          # Non-zero values are what actually make the phone deliver the
          # history-sync blob on (re)login.
          full_sync_config = {
            days_limit = 180;
            size_mb_limit = 100;
            storage_quota_mb = 50;
          };
          media_requests.auto_request_media = true; # fetch expired media on backfill
        };
      };
      # Without this, history-synced conversations are stored but never
      # materialized as messages in the portal rooms (example default: off).
      backfill = {
        enabled = true;
        max_initial_messages = 50;
        max_catchup_messages = 500;
        unread_hours_threshold = 720;
      };
    };
  };

  services.nginx.virtualHosts."matrix.jonbyr.com" = {
    enableACME = true;
    forceSSL = true;
    locations."/" = {
      proxyPass = "http://127.0.0.1:34751";
      proxyWebsockets = true;
      extraConfig = ''
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_request_buffering off;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
      '';
    };
    extraConfig = ''
      access_log /var/log/nginx/matrix_access.log;
      error_log /var/log/nginx/matrix_error.log;
    '';
  };

  services.nginx.virtualHosts."matrix-rtc.jonbyr.com" = {
    enableACME = true;
    forceSSL = true;
    # JWT issuance (lk-jwt-service)
    locations."~ ^/(sfu/get|healthz|get_token)" = {
      proxyPass = "http://127.0.0.1:8091";
      extraConfig = ''
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      '';
    };
    # Livekit (signalling + media over websocket)
    locations."/" = {
      proxyPass = "http://127.0.0.1:7880";
      proxyWebsockets = true;
      extraConfig = ''
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
      '';
    };
    extraConfig = ''
      access_log /var/log/nginx/matrix-rtc_access.log;
      error_log /var/log/nginx/matrix-rtc_error.log;
    '';
  };

  networking.firewall = {
    # MatrixRTC / Livekit: RTC over TCP + TURN. Control ports (7880, 8081)
    # stay loopback-only behind nginx.
    allowedTCPPorts = [7881 3478];
    allowedUDPPorts = [3478];
    allowedUDPPortRanges = [
      {
        from = 50100;
        to = 50200;
      } # Livekit WebRTC media
      {
        from = 50300;
        to = 65535;
      } # Livekit built-in TURN relay
    ];
  };
}
