# Base Dufs configuration (without credentials).

serve-path: "/mnt/storagebox-dufs"
bind: 127.0.0.1
port: 8081

allow-all: false
allow-upload: true
allow-delete: true
allow-search: true
allow-symlink: false
allow-archive: true
allow-hash: false

enable-cors: false

render-index: false
render-try-index: true
render-spa: false

hidden:
  - ".*"
  - "*.log"
  - "*.lock"
  - "blub"

log-format: '$remote_addr "$request" $status'

compress: low
