{
  lib,
  config,
  pkgs,
  inputs,
  ...
}: let
  homeArgs =
    {
      inherit pkgs inputs lib;
      username = "jonas";
      extraPkgs = pkgs: [];
      wsl = config.hm.wsl;
    }
    // {
      inherit (config.hm) standalone useHyprland waybarHeight waybarOpacity;
    };
  mkMonitor = m: let
    bd = lib.optionalString (m.bitdepth != null) ", bitdepth = ${builtins.toString m.bitdepth}";
  in "hl.monitor({ output = \"${m.output}\", mode = \"${m.mode}\", position = \"${m.position}\", scale = \"${m.scale}\"${bd} })";

  # The bulk of the config lives as real .lua files in
  # dotfiles/.config/hypr/. Only the per-machine monitors are generated here.
  monitorsLua = lib.concatStringsSep "\n" (map mkMonitor config.hm.monitors);
in {
  hm.useHyprland = true;

  home.file.".config/hypr/config/monitors.lua".text = ''
    -- Generated by Home-Manager from hm.monitors.
    ${monitorsLua}
  '';

  home.packages = with pkgs; [
    (
      writeShellScriptBin "hyprpaper-ctl"
      (builtins.readFile ../../scripts/hyprpaper-ctl.sh)
    )
    (
      writeShellScriptBin "cmus-control"
      (builtins.readFile ../../scripts/cmus-control.sh)
    )
    (
      writers.writePython3Bin
      "ghostty_wrap"
      {}
      (builtins.readFile ../../scripts/ghostty_wrap.py)
    )
    acpilight
    grim
    slurp
  ];

  programs.waybar = (import ../programs/waybar.nix) homeArgs;
  programs.hyprlock = (import ../programs/hyprlock.nix) homeArgs;
  services.hyprpolkitagent.enable = true;
}
